- hosts: localhost
  become: True
  connection: local
  handlers:
    - include: 'handlers/main.yml'
  vars_files:
    - 'defaults/main.yml'
    - 'vars/main.yml'
    - 'vars/test.yml'
  tasks:
    - include: 'tasks/main.yml'
