---

# commissioning block
- block:
  - name: Create VPC with ec2-vpc role if create_vpc == True
    include_role:
      name: inhumantsar.ec2-vpc
    when: manage_vpc

  - debug: var=vpc_id

  - name: Create instance security group
    ec2_group:
      name: "{{ ec2_cluster_name }}_{{ service_env }}_instances"
      vpc_id: "{{ vpc_id }}"  # this comes from ec2-vpc
      region: "{{vpc_region }}"
      rules: "{{ instance_sg_rules }}"
      description: "some desc"
    register: sg

  - debug: var=sg

  - name: Store security group ID
    set_fact:
      instance_sg_id: "{{ sg.group_id }}"

  - name: Create EC2 keypair if it doesn't already exist
    ec2_key:
      name: "{{ ec2_key_name }}"
      region: "{{ vpc_region }}"
    when: "manage_ec2_keypair == true"

  - name: Create launch config
    ec2_lc:
      name: "{{ ec2_cluster_name }}_{{ service_env }}"
      image_id: "{{ ec2_ami }}"
      key_name: "{{ ec2_key_name }}"
      region: "{{ vpc_region }}"
      security_groups: "{{ instance_sg_id }}"
      instance_type: "{{ ec2_instance_type }}"
    register: lc

  - name: Generate self-signed certificate
    include_role:
      name: jdauphant.ssl-certs
    when: manage_cert

  - name: Create SSL certificate
    local_action:
      module: iam_cert
      name: "{{ ec2_cluster_name }}_{{ service_env }}"
      cert: "/tmp/{{elb_cert_domain}}.pem"
      key: "/tmp/{{elb_cert_domain}}.key"
      # cert_chain: "/tmp/{{elb_cert_domain}}"
      state: present
    when: manage_cert

  # dirty hack to get the active account id so we can build a correct cert ARN.
  # TODO: once ansible 2.4 is out, this http://docs.ansible.com/ansible/iam_cert_facts_module.html
  - name: Install boto3 (it'll be a dep of the ansible modules soon enough anyway)
    pip: name=boto3

  - name: Shell out to aws cli to get the account id
    shell: python -c "import boto3; print(boto3.client('sts').get_caller_identity().get('Account'))"
    register: aws_account_id
  ###

  - name: Build cert arn
    set_fact:
      elb_cert_arn: "arn:aws:iam::{{ aws_account_id.stdout }}:server-certificate/{{ ec2_cluster_name }}_{{ service_env }}"
    when: manage_cert

  - debug: var=vpc_public_subnets

  - name: Create load balancer
    local_action:
      module: ec2_elb_lb
      name: "{{ ec2_cluster_name }}-{{ service_env }}" # ELBs can't have underscores
      region: "{{ vpc_region }}"
      subnets: "{{ vpc_public_subnets }}"
      state: present
      health_check: "{{ elb_health_check }}"
      listeners:
        - protocol: http
          load_balancer_port: 80
          instance_port: "{{ elb_host_port }}"
          proxy_protocol: True
        - protocol: https
          load_balancer_port: 443
          instance_protocol: http
          instance_port: "{{ elb_host_port }}"
          ssl_certificate_id: "{{ elb_cert_arn }}"
    register: lb
    when: manage_elb

  # - debug: var=lb
  - name: Set ELB list when ELB is managed
    set_fact:
      elb_name_list: ["{{ ec2_cluster_name }}-{{ service_env }}"]
    when: manage_elb


  - name: Create autoscaling group
    ec2_asg:
      name: "{{ ec2_cluster_name }}_{{ service_env }}"
      launch_config_name: "{{ ec2_cluster_name }}_{{ service_env }}"
      health_check_period: "{{ asg_health_check_period }}"
      health_check_type: "{{ asg_health_check_type }}"
      replace_all_instances: yes
      max_size: "{{ asg_max_size }}"
      min_size: "{{ asg_min_size }}"
      load_balancers: "{{elb_name_list}}"
      desired_capacity: "{{ asg_desired_capacity }}"
      region: "{{ vpc_region }}"
    register: asg

  when: "service_state != 'absent'"


##########################################
# decommissioning block
- block:
  - name: Get VPC ID for teardown
    local_action:
      module: ec2_vpc_net_facts
      region: "{{ vpc_region }}"
      filters:
        "tag:Name": "{{ vpc_name }}_{{ service_env }}"
    register: vpcs

  - debug: var=vpcs

  - name: Set vpc_id fact from VPC information
    set_fact:
      vpc_id: "{{ vpcs.vpcs[0].id }}"

  - name: Delete autoscaling group
    local_action:
      module: ec2_asg
      name: "{{ ec2_cluster_name }}_{{ service_env }}"
      region: "{{ vpc_region }}"
      state: "{{ service_state }}"
    register: asg

  - name: Delete load balancer
    local_action:
      module: ec2_elb_lb
      name: "{{ ec2_cluster_name }}-{{ service_env }}" # ELBs can't have underscores
      region: "{{ vpc_region }}"
      state: "{{ service_state }}"

  - name: Delete launch config
    local_action:
      module: ec2_lc
      name: "{{ ec2_cluster_name }}_{{ service_env }}"
      region: "{{ vpc_region }}"
      image_id: "{{ ec2_ami }}"
      state: "{{ service_state }}"

  - name: Delete EC2 keypair
    local_action:
      module: ec2_key
      name: "{{ ec2_key_name }}"
      region: "{{ vpc_region }}"
      state: "{{ service_state }}"
    when: manage_ec2_keypair

  - name: Delete instance security group
    local_action:
      module: ec2_group
      name: "{{ ec2_cluster_name }}_{{ service_env }}_instances"
      vpc_id: "{{ vpc_id }}"  # this comes from ec2-vpc
      region: "{{ vpc_region }}"
      state: "{{ service_state }}"

  - name: Delete VPC
    include_role:
      name: inhumantsar.ec2-vpc
      vars:
        service_state: "{{ service_state }}"
    when: manage_vpc
  when: "service_state == 'absent'"
